[phases.setup]
nixPkgs = ["php83", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"